# Generated by Django 5.0.3 on 2024-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('FinalGrade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
